version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    command: ['nginx', '-g', 'daemon off;']
    volumes:
      # nginx
      - ./nginx/nginx-prod.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/error_pages/ERROR403.html:/etc/nginx/ERROR403.html:ro
      - ./templates:/etc/nginx/templates
      # certbot
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    # Не удалось опрокинуть в nginx.conf, но сюда будем дублировать для контроля
    environment:
      - NGINX_HOST=dessly.net
      - NGINX_PORT=80
      - NEXT_PUBLIC_BACKEND_INTERNAL_PORT=8081
      - PG_INTERNAL_PORT=5432
      - FRONTEND_INTERNAL_PORT=3000
#      - PALYCH_NOTIFICATION_POSTBACK_URL=${PALYCH_NOTIFICATION_POSTBACK_URL}
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  deshopfrontend:
    #    image: deshopfrontendCMD pnpm next dev
    container_name: deshopfrontend
    restart: always
    build:
      context: ../deshopfrontend
      dockerfile: ../deshopfrontend/Dockerfile-prod
    volumes:
      - ../deshopfrontend/src:/deshopfrontend/src
      - ../deshopfrontend/public:/deshopfrontend/public
      - ../detools:/detools
    environment:
      - NEXT_PUBLIC_BACKEND_HOST=https://dessly.net
      - NEXT_PUBLIC_BACKEND_EXTERNAL_PORT=${NEXT_PUBLIC_BACKEND_EXTERNAL_PORT}
      - NEXT_PUBLIC_BACKEND_API_NAME=${NEXT_PUBLIC_BACKEND_API_NAME}
      - NEXT_PUBLIC_BACKEND_INTERNAL_PORT=${NEXT_PUBLIC_BACKEND_INTERNAL_PORT}
      - NEXT_PUBLIC_FRONTEND_HOST_NAME=dessly.net
    depends_on:
      - deshopbackend
    expose:
      - "${FRONTEND_INTERNAL_PORT}"

  deshopbackend:
    #    image: deshopbackend
    container_name: deshopbackend
    restart: always
    build:
      context: ../deshopbackend
      dockerfile: ../deshopbackend/Dockerfile-prod
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXT_PUBLIC_BACKEND_HOST=http://dessly.net
      - FRONTEND_HOST=http://dessly.net
      - FRONTEND_HOST_STEAM=http://steam.dessly.net
      - FRONTEND_HOST_ADMIN=http://admin.dessly.net
    volumes:
      - ../deshopfrontend:/deshopfrontend
      - ../detools:/detools
    env_file:
      - ./.env
      - ./.env-secret
    expose:
      - "${NEXT_PUBLIC_BACKEND_INTERNAL_PORT}"

  pg_deshopbackend:
    image: postgres:16.4
    container_name: pg_deshopbackend
    build: ../pg_deshopbackend
    restart: always
    env_file:
      - ./.env
      - ./.env-secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "${PG_INTERNAL_PORT}"

  pg_admin_deshopbackend:
    image: dpage/pgadmin4:8
    container_name: pg_admin_deshopbackend
    build: ../pg_admin_deshopbackend
    depends_on:
      - pg_deshopbackend
    restart: always
    env_file:
      - ./.env
      - ./.env-secret
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./config/servers.json:/pgadmin4/servers.json
      - ./config/certs:/certs
    expose:
      - "${PG_ADMIN_INTERNAL_PORT}"

volumes:
  pgdata:
  pgadmin_data:
